[general]
static=yes
writeprotect=no

[interne]
exten => _10XX,1,NoOp(Appel interne vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},20)
 same => n,GotoIf($["${DIALSTATUS}" = "BUSY"]?occupe:pasdereponse)
 same => n(pasdereponse),VoiceMail(${EXTEN}@default,u)
 same => n,Hangup()
 same => n(occupe),VoiceMail(${EXTEN}@default,b)
 same => n,Hangup()

exten => _200X,1,NoOp(Appel softphone vers ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN},20)
 same => n,VoiceMail(${EXTEN}@default,u)
 same => n,Hangup()

exten => 8000,1,Answer()
 same => n,Set(CHANNEL(language)=fr)
 same => n,Background(custom/welcome-menu)
 same => n,WaitExten(5)

exten => 1,1,Goto(interne,1000,1)
exten => 2,1,Goto(interne,1001,1)
exten => i,1,Playback(invalid)
 same => n,Goto(8000,1)

exten => 8081,1,Answer()
 same => n,NoOp(Test de synthese vocale ou de lecture audio)
 same => n,SayDigits(8081)
 same => n,Hangup()

exten => 236,1,Answer()
 same => n,VoiceMailMain(${CALLERID(num)}@default)
 same => n,Hangup()

exten => 9000,1,ConfBridge(9000)
exten => 9001,1,ConfBridge(9001)
exten => *8,1,Pickup()
